#product-service.h2.console.enabled: true
product-service.datasource.url: jdbc:mysql://localhost:3306/shoppingCartDB
product-service.datasource.username: root
product-service.datasource.password: root
